### ISSUE TITLE
doesn't work on ANY other executors, but only on synapse works

### ISSUE THREAD

**Issue by Liriy** [scotdotwtf/darkrooms#2]
![image](https://user-images.githubusercontent.com/89244602/227992790-7dd8121a-d5ff-4af6-b14f-6c7ae7fd5890.png)

after executing 0 changes, and in workspace folder 0 changes

**Comment by scotdotwtf** [comment]
works on fluxus, just make sure your exploit supports either getcustomasset or getsynasset.
btw if ur wondering on how i could fix this i could change it to not use images from workspace but that is more annoying and i dont want to have to set my themes to use rbx ids since the image could be deleted by roblox.

**Comment by scotdotwtf** [comment]
i will see if i can make it work with valyse tho, havent tested it to see whats going on but will do.

**Comment by scotdotwtf** [comment]
all exploits are like dead now, i’ll update it when another executor comes out lol.
